name: TripTracker
options:
  bundleIdPrefix: com.jamesschliesske
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "1"
    GENERATE_INFOPLIST_FILE: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  TripTracker:
    type: application
    platform: iOS
    sources:
      - path: TripTracker
    info:
      path: TripTracker/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jamesschliesske.triptracker
        DEVELOPMENT_TEAM: 4P8FV64835
        INFOPLIST_KEY_CFBundleDisplayName: TripTracker
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsDocumentBrowser: NO
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
